name: Gumly `main` build and publish
on:
  push:
    branches:
      - main
    paths:
      - 'VERSION'
jobs:
  gumly-main-build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r dev_requirements.txt

      - name: Run build
        run: |
          python -m pip install build
          make build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          # want to get rich logs in case `twine upload` fails for some reason
          verbose: true
          # just in case someone publishes another version by accidentally adding a new line to VERSION
          # we want to skip the existing package and not fail with a 400 if a publish attempt is performed
          skip_existing: true