name: MLUtils PR build
on: pull_request
jobs:
  quick-deploy-pr-build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r dev_requirements.txt

      - name: Run lint
        run: |
          make lint

      - name: Run typecheck
        run: |
          make typecheck

      - name: Run tests
        run: |
          make test
      